name: Build packages
on: [push]
jobs:
  build-ubuntu-packages:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install dependencies
        run: sudo apt-get install -y dh-golang git vim devscripts equivs
      - name: build package
        run: |
          mk-build-deps --install debian/control
          debuild -i -us -uc -b
          dpkg -i ../log-shuttle*.deb
