name: Build packages
on: [push]
env:
  GO_LINKER_SYMBOL: main.version
  GO_BUILD_ENV: GOOS=linux GOARCH=amd64
jobs:
  build-ubuntu-packages:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        releases: [trusty]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - name: Set GO_LINKER_VALUE
        run: |
          echo "GO_LINKER_VALUE=$(git describe --tags --always)" >> $GITHUB_ENV
      - name: Set env
        run: |
          echo "VERSION=$(echo ${GO_LINKER_VALUE} | sed s/^v//)" >> $GITHUB_ENV
          echo "LDFLAGS=-ldflags '-X ${GO_LINKER_SYMBOL}=${GO_LINKER_VALUE}'" >> $GITHUB_ENV
          echo "TMP=$(mktemp -d -t log_shuttle.XXXXX)" >> $GITHUB_ENV
      - name: Build log-shuttle
        run: |
          mkdir -p ${TMP}/DEBIAN
          go build -v -o ${TMP}/usr/bin/log-shuttle ${LDFLAGS} ./cmd/log-shuttle
          cat ./misc/DEBIAN.control | sed s/{{VERSION}}/${VERSION}/ > ${TMP}/DEBIAN/control
